development:
  cloud_name: "hdqlld1cq"
  api_key: "874837483274837"
  api_secret: "a676b67565c6767a6767d6767f676fe1"

production:
  cloud_name: "hdqlld1cq"
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: %= ENV["CLOUDINARY_API_SECRET] %>